spring.application.name=Inventory.Order.Management1

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=inve_mangment
spring.datasource.password=Inv3ntory#2024

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080